/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20BurnableMock__factory } from "./ERC20BurnableMock__factory";
export { VRFCoordinatorMock__factory } from "./VRFCoordinatorMock__factory";
